- set_fact:
    proxy_pass: "{{ item }}"

- set_fact:
    conf_filename: "{% if proxy_pass.server_name == '_' %}catchall_simple_proxy_pass{% else %}{{ proxy_pass.server_name }}{% endif %}"
- name: Check if SSL config is there
  stat: path="/etc/nginx/snippets/{{ conf_filename }}.ssl.conf"
  register: ssl_config_file

- name: Create nginx sites config
  template: src=simple_proxy_pass.conf dest=/etc/nginx/sites-enabled/{{ conf_filename }}.conf
  notify:
    - nginx restart

